development:
  adapter: postgresql
  encoding: unicode
  database: finance_overview_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: finance_overview_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: finance_overview
  pool: 5
