
development:
  adapter: postgresql
  encoding: unicode
  database: spend_app_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spend_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: spend_app
  pool: 5
