
development:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet_usa_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet_usa_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet_usa
  pool: 5
