development:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: spreadsheet
  pool: 5
